name: health
description: Wrapper for HealthKit on iOS and Google Fit and Health Connect on Android.
version: 10.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

environment:
  sdk: ">=2.10.0 <4.0.0"
  flutter: ">=3.7.8"

dependencies:
  flutter:
    sdk: flutter
  intl: "0.17.0"
  device_info_plus: "8.1.0"
  json_annotation: ^4.8.0
  carp_serializable: ^1.1.0 # polymorphic json serialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any

  # Using carp_serializable & json_serializable to auto generate json code (.g files) with this command:
  #   dart run build_runner build --delete-conflicting-outputs
  build_runner: any
  json_serializable: any

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
